cairo http
Hyle-org/verifiers-for-hyle pull request #24
Opened 2024-07-03 10:20 UTC by hhalex

2024-07-03 13:30 UTC, wraitii approved these changes
LGTM -> tu peux peut-être éviter de répéter le code du verifier en important le package?

2024-07-04 08:12 UTC, maxgttph requested changes

2024-07-04 08:12 UTC, maxgttph commented on cairo-verifier/src/utils.rs
> +        program_outputs: input.as_bytes().to_vec(),
je pense qu'on veut plutot mettre ce qui était avant un Event dans program_outputs
C'est probablement le reste de ```parts``` qu'on vuet y mettre!

2024-07-04 08:49 UTC, maximilien-hyle approved these changes

2024-07-04 09:10 UTC, merged